# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  
  build:
    name: continuous-integration
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Check types with ty
        run: |
          set -o pipefail
          uvx ty check | tee ty_output.log
          grep -i found ty_output.log && exit 1 || exit 0